"""
Report generator - turn a run's research findings into a markdown report.

Writes ONLY into a gitignored artifacts dir. Returns the file path. No network, no PRs.
"""
from __future__ import annotations

import os
import time


def generate_report(run, out_dir: str) -> str:
    os.makedirs(out_dir, exist_ok=True)
    lines = [f"# Research report - {run.goal}", "",
             f"- run id: `{run.id}`",
             f"- status: **{getattr(run.status, 'value', run.status)}**",
             f"- generated: {time.strftime('%Y-%m-%dT%H:%M:%S')}", ""]
    total = 0
    for tid, env in run.results.items():
        res = env.result if isinstance(env.result, dict) else None
        if not res or "findings" not in res:
            continue
        lines.append(f"## Task `{tid}` - {res.get('query', '')}")
        lines.append(f"_{res.get('summary', '')}_")
        lines.append("")
        for f in res.get("findings", []):
            total += 1
            title = f.get("title", "")
            url = f.get("url", "")
            src = f.get("source", "")
            conf = f.get("confidence", "")
            snip = f.get("snippet", "")
            head = f"- **{title}** ({src}" + (f", conf={conf}" if conf != "" else "") + ")"
            if url:
                head += f" - {url}"
            lines.append(head)
            if snip:
                lines.append(f"  - {snip}")
        if res.get("source_errors"):
            lines.append(f"  > source errors: {', '.join(res['source_errors'])}")
        lines.append("")
    lines.append(f"---\nTotal findings: {total}. Generated by GARVIS (not committed).")
    path = os.path.join(out_dir, f"report-{run.id}.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return path
