"""
Docs Worker - REAL doc generation, approval-gated, NON-destructive.

Allowed: create/update a markdown document and prepare draft-PR-ready content.
NOT allowed: merge, delete, modify production runtime, or open a PR directly.

Writes only into a gitignored artifacts dir (default runtime/orchestrator/_artifacts/),
never into tracked source. safety_class=WRITE so the Approval Gate must clear it first.
The output dir is injectable (`out_dir=`) so tests write to a temp dir.
"""
from __future__ import annotations

import os

from .base import Worker
from ..models import TaskSpec, Envelope, Status, SafetyClass
from ..registry import WorkerSpec

_DEFAULT_OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                            "_artifacts")


def _slug(text: str) -> str:
    keep = [c.lower() if c.isalnum() else "-" for c in text.strip()]
    s = "".join(keep)
    while "--" in s:
        s = s.replace("--", "-")
    return s.strip("-")[:60] or "untitled"


def render_doc(title: str, body: str = "", findings: list | None = None) -> str:
    lines = [f"# {title}", ""]
    if body:
        lines += [body, ""]
    if findings:
        lines.append("## Findings")
        for f in findings:
            t = f.get("title", "") if isinstance(f, dict) else str(f)
            u = f.get("url", "") if isinstance(f, dict) else ""
            sn = f.get("snippet", "") if isinstance(f, dict) else ""
            lines.append(f"- **{t}** {('(' + u + ')') if u else ''}\n  {sn}".rstrip())
        lines.append("")
    lines.append("_Generated by GARVIS DocsWorker (draft content; not committed)._")
    return "\n".join(lines)


class DocsWorker(Worker):
    spec = WorkerSpec(
        name="docs",
        capabilities=["write_docs", "update_docs"],
        tool_permissions=["fs:write_artifacts"],   # gitignored artifacts only; no PR/merge
        safety_class=SafetyClass.WRITE,             # -> Approval Gate before any write
        cost_class="cheap",
        description="Generate markdown doc content (draft-PR-ready) into gitignored artifacts.",
    )

    def __init__(self, out_dir: str | None = None):
        self.out_dir = out_dir or _DEFAULT_OUT

    def run(self, task: TaskSpec) -> Envelope:
        title = str(task.inputs.get("title", "untitled")).strip() or "untitled"
        body = str(task.inputs.get("body", ""))
        findings = task.inputs.get("findings")
        content = render_doc(title, body, findings if isinstance(findings, list) else None)
        try:
            os.makedirs(self.out_dir, exist_ok=True)
            path = os.path.join(self.out_dir, _slug(title) + ".md")
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
        except Exception as exc:
            return Envelope(task_id=task.id, status=Status.FAILED,
                            error=f"docs write failed: {type(exc).__name__}: {exc}")
        return Envelope(
            task_id=task.id, status=Status.DONE,
            result={"action": "wrote_doc", "path": path, "title": title,
                    "chars": len(content),
                    "draft_pr": {"suggested_path": f"docs/{_slug(title)}.md",
                                 "note": "content ready; opening a DRAFT PR is a separate "
                                         "approval-gated GitHub-worker step (never merge)"}},
            artifacts=[path],
            logs=[f"DocsWorker wrote {len(content)} chars to gitignored artifacts"],
        )
